// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProxyRequestMethod.
const (
	DELETE  ProxyRequestMethod = "DELETE"
	GET     ProxyRequestMethod = "GET"
	HEAD    ProxyRequestMethod = "HEAD"
	OPTIONS ProxyRequestMethod = "OPTIONS"
	PATCH   ProxyRequestMethod = "PATCH"
	POST    ProxyRequestMethod = "POST"
	PUT     ProxyRequestMethod = "PUT"
)

// Valid indicates whether the value is a known member of the ProxyRequestMethod enum.
func (e ProxyRequestMethod) Valid() bool {
	switch e {
	case DELETE:
		return true
	case GET:
		return true
	case HEAD:
		return true
	case OPTIONS:
		return true
	case PATCH:
		return true
	case POST:
		return true
	case PUT:
		return true
	default:
		return false
	}
}

// ParsedSpec defines model for ParsedSpec.
type ParsedSpec struct {
	Id openapi_types.UUID `json:"id"`

	// Raw Original OpenAPI spec as JSON
	Raw     map[string]interface{} `json:"raw"`
	Summary SpecSummary            `json:"summary"`
}

// ProxyRequest defines model for ProxyRequest.
type ProxyRequest struct {
	// Body Request body (any type)
	Body    interface{}        `json:"body,omitempty"`
	Headers *map[string]string `json:"headers,omitempty"`
	Method  ProxyRequestMethod `json:"method"`
	Url     string             `json:"url"`
}

// ProxyRequestMethod defines model for ProxyRequest.Method.
type ProxyRequestMethod string

// ProxyResponse defines model for ProxyResponse.
type ProxyResponse struct {
	// Body Response body (any type)
	Body       interface{}       `json:"body,omitempty"`
	DurationMs *int              `json:"durationMs,omitempty"`
	Headers    map[string]string `json:"headers"`
	Status     int               `json:"status"`
}

// SpecSummary defines model for SpecSummary.
type SpecSummary struct {
	CreatedAt     *time.Time         `json:"createdAt,omitempty"`
	EndpointCount int                `json:"endpointCount"`
	Id            openapi_types.UUID `json:"id"`
	SchemaCount   int                `json:"schemaCount"`
	Tags          *[]string          `json:"tags,omitempty"`
	Title         string             `json:"title"`
	Version       string             `json:"version"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Details *[]struct {
		Field   *string `json:"field,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"details,omitempty"`
	Error *string `json:"error,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Error *string `json:"error,omitempty"`
}

// UploadSpecJSONBody defines parameters for UploadSpec.
type UploadSpecJSONBody = map[string]interface{}

// UploadSpecMultipartBody defines parameters for UploadSpec.
type UploadSpecMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
	Url  *string             `json:"url,omitempty"`
}

// ProxyRequestJSONRequestBody defines body for ProxyRequest for application/json ContentType.
type ProxyRequestJSONRequestBody = ProxyRequest

// UploadSpecJSONRequestBody defines body for UploadSpec for application/json ContentType.
type UploadSpecJSONRequestBody = UploadSpecJSONBody

// UploadSpecMultipartRequestBody defines body for UploadSpec for multipart/form-data ContentType.
type UploadSpecMultipartRequestBody UploadSpecMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// CORS proxy for Try-It-Out requests
	// (POST /proxy)
	ProxyRequest(w http.ResponseWriter, r *http.Request)
	// Upload an OpenAPI specification
	// (POST /specs)
	UploadSpec(w http.ResponseWriter, r *http.Request)
	// Get a stored specification
	// (GET /specs/{id})
	GetSpec(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CORS proxy for Try-It-Out requests
// (POST /proxy)
func (_ Unimplemented) ProxyRequest(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload an OpenAPI specification
// (POST /specs)
func (_ Unimplemented) UploadSpec(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a stored specification
// (GET /specs/{id})
func (_ Unimplemented) GetSpec(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProxyRequest operation middleware
func (siw *ServerInterfaceWrapper) ProxyRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProxyRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadSpec operation middleware
func (siw *ServerInterfaceWrapper) UploadSpec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadSpec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSpec operation middleware
func (siw *ServerInterfaceWrapper) GetSpec(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpec(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/proxy", wrapper.ProxyRequest)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/specs", wrapper.UploadSpec)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/specs/{id}", wrapper.GetSpec)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7SXzXLbNhCAXwWz7aGdoU2lyYk3xVZsd1JLYzm5ZHxYEysJMQkgwNKOxqOZPkSfsE/S",
	"AUhbpMjYau1ebJBcLHa//YPuITelNZo0e8juwZG3RnuKD+eGP5hKy7DOjWbSHJZobaFyZGV0+tUbHd75",
	"fEUlhpV1xpJjVasg54wLC15bggw8O6WXsNkkD2/M9VfKGTbhlSSfO2WDZsjggrypXE5CGxaLaMgmgc9Y",
	"KBkPnzzo3tu2nx0tIIOf0q3Taf3Vp7t6BwzaiogFqoJk9KNREPTP0HmSc0t5n4SKGBfGlciQQVUpCcku",
	"lgQc3gW57sFTp5ZKYyGmlvR4dia8pVygF7/Pp+fQQ5mAr8oS3fo5n4Ol80Y0uOLoW6UcSci+QDQvWLPV",
	"djVw0syZ7+sL+laR577T10au++404iJ8Fb+gXoug9tegbkUoycW9KKUKG7CYdXT2kPVsKolXJuImXZXB",
	"mZPJJSQwm87jv0/x7/jy6BQSOJ58nFxOIIHTyfgYEpjOLs+m5/OWs9uTKld0g+hUP4Y7HBtj6s1PEKzr",
	"bn+EtfwQQ1m5mKR/tHEpzbQk92qMPSNXgwfs+N8Ibo8dYtBOxB6B3BEyyTF32EtkOmBV0lAVkZbWKM1H",
	"pqr7Qp/CnvVYl8oTehiXdX0zlU+yQ+dwHZ8VFzQoeUvOq7ppPZ1Uta1Rz3bXrttd44ewD/TSLnpJjKro",
	"+teVWCgq5KAzJXmPS9qr+fch/bvBofTC9IvkPeY3pKUIHXNhnLggz2Mu0Iu///xLfFa+arXUyXdbGEfu",
	"EWwsskZ+PDtrgc5gdPjmcBTMNJY0WgUZvD0cHb6FBCzyKpJJV4QFr8JySTF5ArdI+0xCBqfx89GK8pvQ",
	"aduD97fR6AUzd1uaD+3P3Ay0s31G8JzcrcpJKC9qb8KcCGKpDV0rnm38gHOdsVDnLnl+3/SyVxnYnSM2",
	"3QphV9HmhVD3OLvp2QPggoAiKdxWpjWV4Wh6MRcRYUzMS7c+OOODacWiIeXjhjTMef9jyp9sYbC+b/x3",
	"xjuDBe/2vGWEEq8KVhYdp6GPHkhkfCoxF6rue49N91rpwOMFk3Ygg5/LgjevlgXd61O/eAK+KoaIpEAt",
	"hY33w+DfuzoZh7Q/mjtwJW3nUB18gboTL7VofGklUHqv5OaHfeiEuMkgiw5L4ng3+HIPKjgR2hkkoLGM",
	"c0/CLuCkBeuZabq5+j9Lcnv3HojFh6oo6ny+U7xqAiFKYoxJGyPy7vmIPP4i6obihFig8GwcyV4UgiS5",
	"2weqXbs+mhwLcUy3VBhbUpzaMfdhxWyzNC2CwMp4zt6ORqM0zJrN1eafAAAA//+xtr/ctw0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
