// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handler

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProxyRequestMethod.
const (
	DELETE  ProxyRequestMethod = "DELETE"
	GET     ProxyRequestMethod = "GET"
	HEAD    ProxyRequestMethod = "HEAD"
	OPTIONS ProxyRequestMethod = "OPTIONS"
	PATCH   ProxyRequestMethod = "PATCH"
	POST    ProxyRequestMethod = "POST"
	PUT     ProxyRequestMethod = "PUT"
)

// Valid indicates whether the value is a known member of the ProxyRequestMethod enum.
func (e ProxyRequestMethod) Valid() bool {
	switch e {
	case DELETE:
		return true
	case GET:
		return true
	case HEAD:
		return true
	case OPTIONS:
		return true
	case PATCH:
		return true
	case POST:
		return true
	case PUT:
		return true
	default:
		return false
	}
}

// ApproveSpecRequest defines model for ApproveSpecRequest.
type ApproveSpecRequest struct {
	// AllowedHosts Optional user-edited host list. Defaults to spec's servers.
	AllowedHosts *[]string `json:"allowedHosts,omitempty"`
}

// DemoInfo defines model for DemoInfo.
type DemoInfo struct {
	Description string `json:"description"`
	Slug        string `json:"slug"`
	Title       string `json:"title"`
}

// ParsedSpec defines model for ParsedSpec.
type ParsedSpec struct {
	Id openapi_types.UUID `json:"id"`

	// Raw Original OpenAPI spec as JSON
	Raw     map[string]interface{} `json:"raw"`
	Summary SpecSummary            `json:"summary"`
}

// ProxyRequest defines model for ProxyRequest.
type ProxyRequest struct {
	// Body Request body (any type)
	Body    interface{}        `json:"body,omitempty"`
	Headers *map[string]string `json:"headers,omitempty"`
	Method  ProxyRequestMethod `json:"method"`

	// SpecId ID of the approved spec this request belongs to
	SpecId openapi_types.UUID `json:"specId"`
	Url    string             `json:"url"`
}

// ProxyRequestMethod defines model for ProxyRequest.Method.
type ProxyRequestMethod string

// ProxyResponse defines model for ProxyResponse.
type ProxyResponse struct {
	// Body Response body (any type)
	Body       interface{}       `json:"body,omitempty"`
	DurationMs *int              `json:"durationMs,omitempty"`
	Headers    map[string]string `json:"headers"`
	Status     int               `json:"status"`
}

// SpecSummary defines model for SpecSummary.
type SpecSummary struct {
	// AllowedHosts Hostnames the proxy may call for this spec
	AllowedHosts []string `json:"allowedHosts"`

	// Approved Whether the user has approved this spec for proxy use
	Approved      bool               `json:"approved"`
	CreatedAt     *time.Time         `json:"createdAt,omitempty"`
	EndpointCount int                `json:"endpointCount"`
	Id            openapi_types.UUID `json:"id"`
	SchemaCount   int                `json:"schemaCount"`
	Tags          *[]string          `json:"tags,omitempty"`
	Title         string             `json:"title"`
	Version       string             `json:"version"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Details *[]struct {
		Field   *string `json:"field,omitempty"`
		Message *string `json:"message,omitempty"`
	} `json:"details,omitempty"`
	Error *string `json:"error,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Error *string `json:"error,omitempty"`
}

// UploadSpecJSONBody defines parameters for UploadSpec.
type UploadSpecJSONBody map[string]interface{}

// ProxyRequestJSONRequestBody defines body for ProxyRequest for application/json ContentType.
type ProxyRequestJSONRequestBody = ProxyRequest

// UploadSpecJSONRequestBody defines body for UploadSpec for application/json ContentType.
type UploadSpecJSONRequestBody UploadSpecJSONBody

// ApproveSpecJSONRequestBody defines body for ApproveSpec for application/json ContentType.
type ApproveSpecJSONRequestBody = ApproveSpecRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List available demo API specs
	// (GET /demos)
	ListDemos(w http.ResponseWriter, r *http.Request)
	// Get the raw OpenAPI spec for a demo
	// (GET /demos/{slug})
	GetDemoSpec(w http.ResponseWriter, r *http.Request, slug string)
	// Parse and store a demo spec, returning its summary
	// (POST /demos/{slug}/load)
	LoadDemo(w http.ResponseWriter, r *http.Request, slug string)

	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// CORS proxy for API requests
	// (POST /proxy)
	ProxyRequest(w http.ResponseWriter, r *http.Request)
	// Upload an OpenAPI specification
	// (POST /specs)
	UploadSpec(w http.ResponseWriter, r *http.Request)
	// Get a stored specification
	// (GET /specs/{id})
	GetSpec(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Approve a spec for proxy use
	// (POST /specs/{id}/approve)
	ApproveSpec(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List available demo API specs
// (GET /demos)
func (_ Unimplemented) ListDemos(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the raw OpenAPI spec for a demo
// (GET /demos/{slug})
func (_ Unimplemented) GetDemoSpec(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Parse and store a demo spec, returning its summary
// (POST /demos/{slug}/load)
func (_ Unimplemented) LoadDemo(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CORS proxy for API requests
// (POST /proxy)
func (_ Unimplemented) ProxyRequest(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload an OpenAPI specification
// (POST /specs)
func (_ Unimplemented) UploadSpec(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a stored specification
// (GET /specs/{id})
func (_ Unimplemented) GetSpec(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Approve a spec for proxy use
// (POST /specs/{id}/approve)
func (_ Unimplemented) ApproveSpec(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDemos operation middleware
func (siw *ServerInterfaceWrapper) ListDemos(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDemos(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDemoSpec operation middleware
func (siw *ServerInterfaceWrapper) GetDemoSpec(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDemoSpec(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LoadDemo operation middleware
func (siw *ServerInterfaceWrapper) LoadDemo(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoadDemo(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProxyRequest operation middleware
func (siw *ServerInterfaceWrapper) ProxyRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProxyRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadSpec operation middleware
func (siw *ServerInterfaceWrapper) UploadSpec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadSpec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSpec operation middleware
func (siw *ServerInterfaceWrapper) GetSpec(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSpec(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveSpec operation middleware
func (siw *ServerInterfaceWrapper) ApproveSpec(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveSpec(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/demos", wrapper.ListDemos)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/demos/{slug}", wrapper.GetDemoSpec)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/demos/{slug}/load", wrapper.LoadDemo)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/proxy", wrapper.ProxyRequest)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/specs", wrapper.UploadSpec)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/specs/{id}", wrapper.GetSpec)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/specs/{id}/approve", wrapper.ApproveSpec)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xY3W7bNhR+FYIbsA1QI3ftle/cOG0ypHUQpx2GoheMeGyxpUiWpJJ6gYE9xJ5wTzIc",
	"UrYkS/7JnPWmVWya55zvO/zORz3QTBdGK1De0eEDteCMVg7CH++0f61LxfE508qD8vjIjJEiY15olX52",
	"WuFnLsuhYPhkrDZgvYhbgLXa4oNfGKBD6rwVak6Xy2T1ib79DJmnS/yIg8usMLgzHdJrcLq0GRClPZmF",
	"RJYJ/cCk4CH42Wrvg3P70cKMDukPaV10Gr916ea+PQnVS8iMCQk81FFtgPuPjLH6DqYGsmv4WoLzXUSY",
	"lPoe+Ll2EfF2iEl4YJKUDuwz4MIDJ7l2nkjh/AkZw4yV0jviNXEGsp8ccWDvwLoTmlDhoXA9aK/BZtay",
	"RR/6CR1DoS/UTHczbmXYs7eT5bw/qPAS+sm38LUUFjgdfoy/X61uY/6pJ9ErZh1wxLibqgi9OtO2YJ4O",
	"aVkKTpNuYpbdByo4FxHuq8Yu3pawyfzEirlAWiYG1OjqImBPmCO/TSfvaE+SriwKZhf7mg6rmFZLN2EJ",
	"qWOm9W69cFj9bbG12241X3S7rFpO8FvyM1MLgtv+gtvlwDhYtx2e7c1V51SAz3WgAlRZYDFvzm5oQq8m",
	"0/Df+/Dv6Ob0nCZ0fHZ5dnNGE3p+NhrThE6ubi4m76aNYhutZiC74N2CLsZEz4jPgbB4BHlkyOfCEbuq",
	"FqRWczw6NNnfI6WV7V6yortsg7Kq7vjjdbY7WItiezhtcX0fb7y0QZneNikSysMc7JPx6jzzZW+AzSMd",
	"F9Zh+zBoNv8jZRI/VqwAFzg3CCYp2IJkTEoy0zYSj/g/QhUTumqebsDfc/A52BAOpZnkzNW9to4WYsd0",
	"Sgd1v9xqLYEpjJFZYB74yLe6izMPz7wooK8VQXGjhfKnuoxTrkvvgcIXdWfHPp7No5AejNk2kU8oTqX+",
	"mdGndCv5X/1qs+x28g2uknav9HVaj2fYHHGeCdmuvL1iJkDy3jILcI7N4SCT04XvcQZJVAO63ZyvWPYF",
	"FCc4mLABr+HrB/En+eevv8kH4crG2Dr7ZqS2YNd4h1mAi0dXFw3wh3Rw8vxkgAlqA4oZQYf0xcng5AVN",
	"qGE+D5ikHAodnuYQ+gkBCzCjRtNL4fw4rEjavvLXweBRtm1Nya5RuvYvXbfTMXIj/AInBhZACvCMM8+i",
	"m1sJUkifsDsmJLuVEJeuRr8La2P96QMamOVWGN5AQGEaxcgwywrwQYo/PlCB6SCgNKEoaNgB0Q7VByQa",
	"khqOzU75dCS8u2zQfpPO7iM0LUe0TOjLwcttlK2zTdc3jDb0b8AHpbXsvu24sLtZiNclIJWahRNqtOvr",
	"Rs048vC9OHj+ZDeTtknsMDBeo2+CMyZMceK8xryP5CFY7Xq/CvoQLCEWfGmVUHMivCOu4WLTHJj0+dYT",
	"cR6+Ps0h+3KsNLRFuvYnK9+pv/T4yEMun1OwdyIDIhyJ1QTssbgw3rf3WcuPxxYC519Vhu5JGqIVYtme",
	"ptioyyNBPSB2ZVx7gMMFAjix9ZpmS51OrqeVQ8LDjCe7gqjS1CivW+F9b/CYV2L6X8E9/OJ3valAW+98",
	"0T6ug357tmCFbIfdv/Ufo7eXPbeMAxj+bnKDX5MysFBpTZSdqDWD/VrTfdHS7I/IL2GqhY2YVbU0eiR9",
	"EHzn1D144sab9lat3+Oqj56/O49b/bKjh4vXpZSxd+6Fz1f6X/uZ46cwqybJbhbSyoxvP7aNN2PfjZKn",
	"F96e93vL6nT+T/zvOYzvDV4cq5cd6xF8HO1VkUh990YbcqjeOAbu2vlc6oxJMoY7kNoUEC5q4UUKzb03",
	"wzSVuCDXzg9fDAaDFC8Wy0/LfwMAAP//dzibtIYWAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
