package parser

import (
	"fmt"

	"gopkg.in/yaml.v3"
)

// FromYAML parses a YAML byte slice into a validated ParseResult.
func FromYAML(data []byte) (*ParseResult, error) {
	var raw map[string]any
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("invalid YAML: %w", err)
	}
	raw = sanitizeMap(raw).(map[string]any)
	return extract(data, raw)
}

// sanitizeMap recursively converts map[interface{}]interface{} generated by
// gopkg.in/yaml.v3 into map[string]any to ensure the map is JSON-compatible.
func sanitizeMap(v any) any {
	switch x := v.(type) {
	case map[interface{}]interface{}:
		m := make(map[string]any)
		for k, val := range x {
			m[fmt.Sprintf("%v", k)] = sanitizeMap(val)
		}
		return m
	case map[string]any:
		for k, val := range x {
			x[k] = sanitizeMap(val)
		}
		return x
	case []any:
		for i, val := range x {
			x[i] = sanitizeMap(val)
		}
		return x
	default:
		return v
	}
}
